package com.snowmangame;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.*;
import android.os.Build;
import android.os.Bundle;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowInsets;

/** Active second-grade chapter. The first day introduces a newcomer, later days remain replayable. */
public class GradeTwoActivity extends Activity {
    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        Window w=getWindow();
        if(Build.VERSION.SDK_INT>=21){
            w.setStatusBarColor(Color.TRANSPARENT);
            w.setNavigationBarColor(Color.rgb(236,247,252));
            int flags=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            if(Build.VERSION.SDK_INT>=26)flags|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
            w.getDecorView().setSystemUiVisibility(flags);
        }
        if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);
        getSharedPreferences("snowman_game",MODE_PRIVATE).edit().putBoolean("class2_started",true).putInt("school_grade",2).putInt("school_winter",8).apply();
        setContentView(new GradeTwoView(this));
    }

    static class GradeTwoView extends View {
        static final int WELCOME=0, MEET=1, DESK=2, ROUTE=3, YARD=4, DONE=5;
        final Context ctx; final SharedPreferences prefs;
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),text=new Paint(Paint.ANTI_ALIAS_FLAG),stroke=new Paint(Paint.ANTI_ALIAS_FLAG);
        final RectF action=new RectF(),memoryBtn=new RectF(),wardrobeBtn=new RectF();
        final RectF[] desks={new RectF(),new RectF(),new RectF()};
        final RectF[] routes={new RectF(),new RectF(),new RectF()};
        final RectF[] targets={new RectF(),new RectF(),new RectF()};
        final float density,textScale; final Vibrator vibrator;
        float safeTop,safeBottom; int stage,mistakes,yardMask,day; String feedback="";

        GradeTwoView(Context c){
            super(c);ctx=c;prefs=c.getSharedPreferences("snowman_game",Context.MODE_PRIVATE);
            density=getResources().getDisplayMetrics().density;
            textScale=Math.min(getResources().getDisplayMetrics().scaledDensity,density*1.15f);
            vibrator=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);
            stage=Math.max(WELCOME,Math.min(DONE,prefs.getInt("class2_stage",WELCOME)));
            mistakes=Math.max(0,prefs.getInt("school_mistakes",0));
            yardMask=prefs.getInt("class2_yard_mask",0)&7;
            day=Math.max(1,prefs.getInt("class2_days",1));
            SnowmanStyle.ensureUnlocked(prefs,7);
            text.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeCap(Paint.Cap.ROUND);
            setClickable(true);setFocusable(true);setContentDescription("Другий клас 2-А: допомогти новачку Іскрику та прожити шкільний день");
            setOnApplyWindowInsetsListener(new OnApplyWindowInsetsListener(){@Override public WindowInsets onApplyWindowInsets(View v,WindowInsets i){safeTop=i.getSystemWindowInsetTop();safeBottom=i.getSystemWindowInsetBottom();invalidate();return i;}});requestApplyInsets();
        }

        float dp(float v){return v*density;} float tx(float v){return v*textScale;}
        void buzz(int ms){if(vibrator==null||!vibrator.hasVibrator())return;if(Build.VERSION.SDK_INT>=26)vibrator.vibrate(VibrationEffect.createOneShot(ms,70));else vibrator.vibrate(ms);}
        void setStage(int s){stage=s;feedback="";prefs.edit().putInt("class2_stage",s).apply();buzz(18);SoundFx.play(ctx,SoundFx.UI);invalidate();}
        void wrong(String s){mistakes++;feedback=s;prefs.edit().putInt("school_mistakes",mistakes).apply();buzz(10);SoundFx.play(ctx,SoundFx.WRONG);invalidate();}
        void correct(String s){feedback=s;buzz(24);SoundFx.play(ctx,SoundFx.CORRECT);invalidate();}
        String title(){if(stage==WELCOME)return"Перший день у 2-А";if(stage==MEET)return"Новенький";if(stage==DESK)return"Допоможи знайти парту";if(stage==ROUTE)return"Історія мандрів";if(stage==YARD)return"Перерва удвох";return"День 2-А прожито";}
        String sub(){if(stage==WELCOME)return"Ти вже не наймолодший. Сьогодні допомога потрібна комусь іншому.";if(stage==MEET)return"Пан Криж привів нового учня — Іскрика.";if(stage==DESK)return"Його місце — середня парта біля вікна зі знаком сніжинки.";if(stage==ROUTE)return"Іскрик почув, що ти пройшов сім областей, і просить показати останню.";if(stage==YARD)return"Покажи новачку шкільне подвір’я: разом влучте у три мішені.";return"Іскрик уже знає клас, парту й подвір’я.";}

        @Override protected void onDraw(Canvas c){super.onDraw(c);drawBackground(c);drawHeader(c);if(stage==WELCOME)drawWelcome(c);else if(stage==MEET)drawMeet(c);else if(stage==DESK)drawDeskTask(c);else if(stage==ROUTE)drawRoute(c);else if(stage==YARD)drawYard(c);else drawDone(c);}

        void drawBackground(Canvas c){float w=getWidth(),h=getHeight(),bottom=h-safeBottom;if(stage==YARD){LinearGradient g=new LinearGradient(0,0,0,bottom,Color.rgb(158,218,246),Color.rgb(238,249,253),Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.rgb(247,252,254));c.drawRect(0,bottom*.68f,w,h,p);}else{LinearGradient g=new LinearGradient(0,0,0,bottom,Color.rgb(241,235,213),Color.rgb(226,220,198),Shader.TileMode.CLAMP);p.setShader(g);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.rgb(191,154,109));c.drawRect(0,bottom-dp(82),w,h,p);}}

        void drawHeader(Canvas c){float w=getWidth(),top=safeTop+dp(10);RectF r=new RectF(dp(14),top,w-dp(14),top+dp(108));p.setColor(Color.argb(247,255,255,255));c.drawRoundRect(r,dp(24),dp(24),p);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(tx(7.2f));text.setColor(Color.rgb(102,129,143));c.drawText("ШКОЛА • ЗИМА 8 • 2-А • ДЕНЬ "+day,r.left+dp(17),r.top+dp(20),text);text.setTextSize(tx(18));text.setColor(Color.rgb(37,73,94));c.drawText(title(),r.left+dp(17),r.top+dp(51),text);String s=sub();text.setTextSize(tx(7.6f));while(text.measureText(s)>r.width()-dp(34)&&text.getTextSize()>tx(5.2f))text.setTextSize(text.getTextSize()-dp(.25f));text.setColor(Color.rgb(91,124,141));c.drawText(s,r.left+dp(17),r.top+dp(78),text);text.setTextAlign(Paint.Align.RIGHT);text.setTextSize(tx(6.5f));text.setColor(Color.rgb(128,143,149));c.drawText("помилки "+mistakes,r.right-dp(17),r.bottom-dp(13),text);}

        void drawWelcome(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF room=new RectF(dp(20),safeTop+dp(140),w-dp(20),bottom-dp(95));p.setColor(Color.argb(243,255,255,255));c.drawRoundRect(room,dp(25),dp(25),p);drawBoard(c,room,"2-А • НОВА ЗИМА");float ground=room.bottom-dp(38);drawHero(c,room.left+room.width()*.24f,ground,dp(34),.25f);drawTeacher(c,room.left+room.width()*.70f,ground,dp(38));drawNewcomer(c,room.left+room.width()*.86f,ground,dp(25));text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(10));text.setColor(Color.rgb(53,87,104));c.drawText("Пан Криж: «Сьогодні у нас новенький.»",room.centerX(),room.top+dp(130),text);text.setTextSize(tx(7.5f));text.setColor(Color.rgb(101,126,137));c.drawText("У першому класі допомагали тобі. Тепер твоя черга.",room.centerX(),room.top+dp(158),text);button(c,"ПОЗНАЙОМИТИСЯ З НОВАЧКОМ");}

        void drawMeet(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF card=new RectF(dp(22),safeTop+dp(142),w-dp(22),bottom-dp(95));p.setColor(Color.argb(244,255,255,255));c.drawRoundRect(card,dp(25),dp(25),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(7));text.setColor(Color.rgb(111,132,139));c.drawText("ІСКРИК • НОВИЙ УЧЕНЬ 2-А",card.centerX(),card.top+dp(28),text);text.setTextSize(tx(13));text.setColor(Color.rgb(48,82,99));c.drawText("«Я тут нікого не знаю… і навіть не бачу свою парту.»",card.centerX(),card.top+dp(66),text);float ground=card.bottom-dp(42);drawHero(c,card.centerX()-dp(62),ground,dp(35),.5f);drawNewcomer(c,card.centerX()+dp(62),ground,dp(28));text.setTextSize(tx(8));text.setColor(Color.rgb(92,120,134));c.drawText("Покажемо, що 2-А не страшний.",card.centerX(),card.top+dp(105),text);button(c,"ДОПОМОГТИ ІСКРИКУ");}

        void drawDeskTask(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF scene=new RectF(dp(20),safeTop+dp(140),w-dp(20),bottom-dp(95));p.setColor(Color.argb(244,255,255,255));c.drawRoundRect(scene,dp(25),dp(25),p);drawBoard(c,scene,feedback.length()>0?feedback:"СЕРЕДНЯ ПАРТА • ЗНАК СНІЖИНКИ");for(int i=0;i<3;i++){float dw=(scene.width()-dp(72))/3f,x=scene.left+dp(18)+i*(dw+dp(18)),top=scene.top+dp(128);desks[i].set(x,top,x+dw,scene.bottom-dp(48));drawDesk(c,desks[i],i==1);}p.setColor(Color.rgb(151,210,235));c.drawRoundRect(new RectF(scene.right-dp(65),scene.top+dp(76),scene.right-dp(20),scene.top+dp(118)),dp(5),dp(5),p);text.setTextAlign(Paint.Align.RIGHT);text.setTextSize(tx(6));text.setColor(Color.rgb(91,124,141));c.drawText("ВІКНО",scene.right-dp(23),scene.top+dp(70),text);}

        void drawRoute(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF card=new RectF(dp(20),safeTop+dp(140),w-dp(20),bottom-dp(95));p.setColor(Color.argb(244,255,255,255));c.drawRoundRect(card,dp(25),dp(25),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(12));text.setColor(Color.rgb(48,82,99));c.drawText(day==1?"«А де закінчилися твої сім мандрів?»":"Іскрик знову просить показати маршрут",card.centerX(),card.top+dp(46),text);text.setTextSize(tx(7.2f));text.setColor(Color.rgb(101,126,138));c.drawText(feedback.length()>0?feedback:"Торкнись останньої області маршруту.",card.centerX(),card.top+dp(76),text);String[] names={"КИЇВЩИНА","ОДЕЩИНА","ТЕРНОПІЛЬЩИНА"};float gap=dp(10),left=card.left+dp(16),right=card.right-dp(16),top=card.top+dp(113),rw=(right-left-gap*2)/3f;for(int i=0;i<3;i++){routes[i].set(left+i*(rw+gap),top,left+i*(rw+gap)+rw,top+dp(125));p.setColor(i==2?Color.rgb(237,249,253):Color.rgb(248,250,250));c.drawRoundRect(routes[i],dp(18),dp(18),p);drawRegionMark(c,routes[i],i);text.setTextSize(tx(6.6f));text.setColor(Color.rgb(60,105,130));c.drawText(names[i],routes[i].centerX(),routes[i].bottom-dp(17),text);}float ground=card.bottom-dp(38);drawHero(c,card.centerX()-dp(48),ground,dp(31),.4f);drawNewcomer(c,card.centerX()+dp(52),ground,dp(25));}

        void drawYard(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF info=new RectF(dp(22),safeTop+dp(142),w-dp(22),safeTop+dp(225));p.setColor(Color.argb(242,255,255,255));c.drawRoundRect(info,dp(21),dp(21),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(9));text.setColor(Color.rgb(58,91,107));c.drawText(feedback.length()>0?feedback:"Торкнись трьох снігових мішеней",info.centerX(),info.top+dp(34),text);text.setTextSize(tx(6.8f));text.setColor(Color.rgb(102,128,139));c.drawText("Іскрик повторює за тобою.",info.centerX(),info.bottom-dp(18),text);float[] xs={w*.25f,w*.52f,w*.78f},ys={safeTop+dp(320),safeTop+dp(390),safeTop+dp(305)};for(int i=0;i<3;i++){targets[i].set(xs[i]-dp(37),ys[i]-dp(37),xs[i]+dp(37),ys[i]+dp(37));boolean hit=(yardMask&(1<<i))!=0;drawTarget(c,xs[i],ys[i],dp(28),hit);}float ground=bottom-dp(77);drawHero(c,w*.31f,ground,dp(31),.7f);drawNewcomer(c,w*.68f,ground,dp(26));if(yardMask==7)button(c,"ЗАВЕРШИТИ ДЕНЬ 2-А");else action.setEmpty();}

        void drawDone(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF card=new RectF(dp(20),safeTop+dp(140),w-dp(20),bottom-dp(185));p.setColor(Color.argb(244,255,255,255));c.drawRoundRect(card,dp(27),dp(27),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(7));text.setColor(Color.rgb(108,132,140));c.drawText("2-А • ДЕНЬ "+day,card.centerX(),card.top+dp(27),text);text.setTextSize(tx(21));text.setColor(Color.rgb(42,108,146));c.drawText("ІСКРИК ВЖЕ НЕ САМОТНІЙ",card.centerX(),card.top+dp(66),text);text.setTextSize(tx(8.2f));text.setColor(Color.rgb(92,122,136));c.drawText("Ти знайшов йому парту, розповів про мандри й показав подвір’я.",card.centerX(),card.top+dp(96),text);RectF badge=new RectF(card.left+dp(25),card.top+dp(125),card.right-dp(25),card.top+dp(169));p.setColor(Color.rgb(232,246,238));c.drawRoundRect(badge,dp(15),dp(15),p);text.setTextSize(tx(8));text.setColor(Color.rgb(55,126,101));c.drawText("ДОВІРА ІСКРИКА +1 • ДНІВ У 2-А: "+day,badge.centerX(),badge.centerY()+dp(3),text);float ground=card.bottom-dp(32);drawHero(c,card.centerX()-dp(55),ground,dp(35),.7f);drawNewcomer(c,card.centerX()+dp(58),ground,dp(28));float gap=dp(8),half=(w-dp(48)-gap)/2f;memoryBtn.set(dp(20),bottom-dp(174),dp(20)+half,bottom-dp(121));wardrobeBtn.set(memoryBtn.right+gap,bottom-dp(174),w-dp(20),bottom-dp(121));p.setColor(Color.rgb(232,242,237));c.drawRoundRect(memoryBtn,dp(17),dp(17),p);p.setColor(Color.rgb(234,242,247));c.drawRoundRect(wardrobeBtn,dp(17),dp(17),p);text.setTextSize(tx(8));text.setColor(Color.rgb(58,106,91));c.drawText("СПОГАДИ",memoryBtn.centerX(),memoryBtn.centerY()+dp(3),text);text.setColor(Color.rgb(61,103,127));c.drawText("ГАРДЕРОБ",wardrobeBtn.centerX(),wardrobeBtn.centerY()+dp(3),text);button(c,"ЩЕ ОДИН ДЕНЬ У 2-А");}

        void button(Canvas c,String label){float w=getWidth(),bottom=getHeight()-safeBottom;action.set(dp(22),bottom-dp(66),w-dp(22),bottom-dp(11));p.setColor(Color.rgb(37,108,153));c.drawRoundRect(action,dp(20),dp(20),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(9.2f));while(text.measureText(label)>action.width()-dp(28)&&text.getTextSize()>tx(6.2f))text.setTextSize(text.getTextSize()-dp(.25f));text.setColor(Color.WHITE);c.drawText(label,action.centerX(),action.centerY()+dp(4),text);}
        void drawBoard(Canvas c,RectF r,String label){RectF b=new RectF(r.left+dp(18),r.top+dp(18),r.right-dp(18),r.top+dp(72));p.setColor(Color.rgb(64,101,84));c.drawRoundRect(b,dp(8),dp(8),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(10));text.setColor(Color.WHITE);c.drawText(label,b.centerX(),b.centerY()+dp(4),text);}
        void drawDesk(Canvas c,RectF r,boolean mark){p.setColor(Color.rgb(174,126,78));c.drawRoundRect(new RectF(r.left,r.top+dp(38),r.right,r.top+dp(80)),dp(8),dp(8),p);stroke.setColor(Color.rgb(112,78,52));stroke.setStrokeWidth(dp(4));c.drawLine(r.left+dp(13),r.top+dp(79),r.left+dp(8),r.bottom,stroke);c.drawLine(r.right-dp(13),r.top+dp(79),r.right-dp(8),r.bottom,stroke);if(mark){float x=r.centerX(),y=r.top+dp(59),rr=dp(10);stroke.setColor(Color.rgb(61,151,201));stroke.setStrokeWidth(dp(2));for(int i=0;i<6;i++){double a=i*Math.PI/3;c.drawLine(x,y,x+(float)Math.cos(a)*rr,y+(float)Math.sin(a)*rr,stroke);}p.setColor(Color.rgb(61,151,201));c.drawCircle(x,y,dp(2.3f),p);}}
        void drawRegionMark(Canvas c,RectF r,int i){float x=r.centerX(),y=r.top+dp(44);p.setColor(i==2?Color.rgb(61,151,201):(i==1?Color.rgb(224,166,79):Color.rgb(88,137,169)));c.drawCircle(x,y,dp(17),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(12));text.setColor(Color.WHITE);c.drawText(i==0?"1":(i==1?"4":"7"),x,y+dp(4),text);}
        void drawTarget(Canvas c,float x,float y,float r,boolean hit){p.setColor(hit?Color.rgb(209,231,237):Color.rgb(250,253,254));c.drawCircle(x,y,r,p);stroke.setColor(hit?Color.rgb(61,151,201):Color.rgb(110,153,177));stroke.setStrokeWidth(dp(3));c.drawCircle(x,y,r,stroke);c.drawCircle(x,y,r*.58f,stroke);c.drawCircle(x,y,r*.22f,stroke);if(hit){text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(18));text.setColor(Color.rgb(55,126,101));c.drawText("✓",x,y+dp(6),text);}}

        void drawHero(Canvas c,float x,float ground,float r,float wave){drawPerson(c,x,ground,r,wave,true,false);}
        void drawNewcomer(Canvas c,float x,float ground,float r){drawPerson(c,x,ground,r,.15f,false,true);}
        void drawPerson(Canvas c,float x,float ground,float r,float wave,boolean hero,boolean newcomer){float br=r,mr=r*.72f,hr=r*.53f,by=ground-br,my=by-(br+mr)*.84f,hy=my-(mr+hr)*.84f;snow(c,x,by,br);snow(c,x,my,mr);snow(c,x,hy,hr);p.setColor(Color.rgb(44,59,68));c.drawCircle(x-hr*.28f,hy-hr*.14f,hr*.08f,p);c.drawCircle(x+hr*.28f,hy-hr*.14f,hr*.08f,p);Path n=new Path();n.moveTo(x,hy);n.lineTo(x+hr*.68f,hy+hr*.07f);n.lineTo(x,hy+hr*.14f);n.close();p.setColor(Color.rgb(241,117,34));c.drawPath(n,p);stroke.setColor(Color.rgb(105,78,57));stroke.setStrokeWidth(Math.max(dp(2.5f),r*.075f));float lx=x-mr*.60f,ly=my,lxe=x-mr*1.35f,lye=my-mr*(.25f+.12f*wave),rx=x+mr*.60f,ry=my,rxe=x+mr*(1.35f+wave*.10f),rye=my-mr*(.25f+.15f*wave);c.drawLine(lx,ly,lxe,lye,stroke);c.drawLine(rx,ry,rxe,rye,stroke);if(hero){int o=SnowmanStyle.outfit(prefs,7);if(o>0){SnowmanStyle.drawSleeve(c,p,stroke,density,lx,ly,x-mr*1.23f,my-mr*.22f,mr*.35f,o);SnowmanStyle.drawSleeve(c,p,stroke,density,rx,ry,x+mr*(1.23f+wave*.06f),my-mr*(.22f+.10f*wave),mr*.35f,o);}SnowmanStyle.drawFaceAccent(c,p,stroke,density,SnowmanStyle.character(prefs),x,hy,hr);}else if(newcomer){p.setColor(Color.rgb(88,154,181));c.drawRoundRect(new RectF(x-mr*.64f,my-mr*.72f,x+mr*.64f,my-mr*.53f),dp(4),dp(4),p);p.setColor(Color.rgb(252,190,24));c.drawCircle(x+hr*.52f,hy-hr*.54f,dp(4.5f),p);}}
        void drawTeacher(Canvas c,float x,float ground,float r){float br=r,mr=r*.74f,hr=r*.55f,by=ground-br,my=by-(br+mr)*.82f,hy=my-(mr+hr)*.82f;snow(c,x,by,br);snow(c,x,my,mr);snow(c,x,hy,hr);p.setColor(Color.rgb(45,59,68));c.drawCircle(x-hr*.27f,hy-hr*.12f,hr*.07f,p);c.drawCircle(x+hr*.27f,hy-hr*.12f,hr*.07f,p);stroke.setColor(Color.rgb(52,67,76));stroke.setStrokeWidth(dp(1.6f));c.drawCircle(x-hr*.27f,hy-hr*.12f,hr*.18f,stroke);c.drawCircle(x+hr*.27f,hy-hr*.12f,hr*.18f,stroke);c.drawLine(x-hr*.09f,hy-hr*.12f,x+hr*.09f,hy-hr*.12f,stroke);p.setColor(Color.rgb(64,83,94));c.drawRoundRect(new RectF(x-mr*.52f,my-mr*.52f,x+mr*.52f,my+mr*.42f),dp(7),dp(7),p);RectF collar=new RectF(x-mr*.41f,my-mr*.59f,x+mr*.41f,my-mr*.47f);SnowmanStyle.drawPatternBand(c,p,density,collar,7);}
        void snow(Canvas c,float x,float y,float r){RadialGradient g=new RadialGradient(x-r*.30f,y-r*.35f,r*1.4f,new int[]{Color.WHITE,Color.rgb(247,252,255),Color.rgb(198,227,242)},null,Shader.TileMode.CLAMP);p.setShader(g);c.drawCircle(x,y,r,p);p.setShader(null);stroke.setColor(Color.argb(65,90,146,174));stroke.setStrokeWidth(dp(1));c.drawCircle(x,y,r-dp(.5f),stroke);}

        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;performClick();float x=e.getX(),y=e.getY();if(stage==WELCOME&&action.contains(x,y)){setStage(MEET);return true;}if(stage==MEET&&action.contains(x,y)){setStage(DESK);return true;}if(stage==DESK){for(int i=0;i<3;i++)if(desks[i].contains(x,y)){if(i==1){prefs.edit().putBoolean("class2_newcomer_seated",true).putString("class2_newcomer_name","Іскрик").apply();correct("Ось вона. Іскрик сідає поруч із вікном.");setStage(ROUTE);}else wrong("Не ця. Пан Криж сказав: середня парта зі сніжинкою.");return true;}}if(stage==ROUTE){for(int i=0;i<3;i++)if(routes[i].contains(x,y)){if(i==2){prefs.edit().putBoolean("class2_route_shared",true).apply();correct("Тернопільщина. Тут мандри стали школою.");setStage(YARD);}else wrong("Це була частина маршруту, але не остання область.");return true;}}if(stage==YARD){for(int i=0;i<3;i++)if(targets[i].contains(x,y)&&((yardMask&(1<<i))==0)){yardMask|=1<<i;prefs.edit().putInt("class2_yard_mask",yardMask).apply();SoundFx.play(ctx,SoundFx.HIT);buzz(14);if(yardMask==7){prefs.edit().putBoolean("class2_first_day_complete",true).apply();correct("Три з трьох. Іскрик уже сміється разом із тобою.");}else invalidate();return true;}if(yardMask==7&&action.contains(x,y)){int trust=Math.max(1,prefs.getInt("class2_iskryk_trust",0)+1);prefs.edit().putInt("class2_iskryk_trust",trust).putInt("class2_stage",DONE).apply();stage=DONE;SoundFx.play(ctx,SoundFx.COMPLETE);invalidate();return true;}}if(stage==DONE){if(memoryBtn.contains(x,y)){ctx.startActivity(new Intent(ctx,MemoryActivity.class));return true;}if(wardrobeBtn.contains(x,y)){ctx.startActivity(new Intent(ctx,WardrobeActivity.class));return true;}if(action.contains(x,y)){day++;yardMask=0;feedback="";prefs.edit().putInt("class2_days",day).putInt("class2_yard_mask",0).putInt("class2_stage",ROUTE).apply();stage=ROUTE;SoundFx.play(ctx,SoundFx.SCHOOL_BELL);invalidate();return true;}}return true;}
        @Override public boolean performClick(){super.performClick();return true;}
    }
}
