package com.snowmangame;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.*;
import android.os.Build;
import android.os.Bundle;
import android.os.SystemClock;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowInsets;

import java.util.ArrayList;
import java.util.Iterator;
import java.util.Random;

public class MainActivity extends Activity {
    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        Window w=getWindow();
        if(Build.VERSION.SDK_INT>=21){
            w.setStatusBarColor(Color.TRANSPARENT);
            w.setNavigationBarColor(Color.rgb(235,247,253));
            int flags=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;
            if(Build.VERSION.SDK_INT>=26)flags|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;
            w.getDecorView().setSystemUiVisibility(flags);
        }
        if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);
        setContentView(new SnowmanView(this));
    }

    static class SnowmanView extends View{
        static final int EYES=0,NOSE=1,BUTTONS=2,SCARF=3,HAT=4,ARMS=5,ACCESSORY_COUNT=6;
        final Context ctx;
        final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),text=new Paint(Paint.ANTI_ALIAS_FLAG),stroke=new Paint(Paint.ANTI_ALIAS_FLAG);
        final Random rnd=new Random();
        final ArrayList<Dust> dust=new ArrayList<>();
        final Accessory[] accessories=new Accessory[ACCESSORY_COUNT];
        final float density,textScale;
        final Vibrator vib;
        final SharedPreferences prefs;

        float safeTop,safeBottom;
        boolean compact,narrow,finished,sponsorScene,sponsorRewarded,coinsAwarded;
        int balls,score,bestScore,qualitySum,decorQualitySum,decorPlaced,combo,maxCombo;
        int year,wallet,runCoins,mission;
        long startTime,sponsorStart;
        int finishElapsed;
        boolean missionSuccess;
        String tip="Коти сніг пальцем — зроби першу кулю";

        float rollProgress,rollX=Float.NaN,rollY=Float.NaN,lastX,lastY,lastDx,lastDy,turnPenalty;
        boolean rolling,draggingBall,ballReady;
        int draggingAccessory=-1;
        float dragAccessoryX,dragAccessoryY;

        final RectF hudRect=new RectF(),tipRect=new RectF(),interactionRect=new RectF(),finishBtn=new RectF();
        final RectF sponsorBtn=new RectF(),stationBtn=new RectF(),replayBtn=new RectF(),sponsorCloseBtn=new RectF();
        float playTop,playBottom,baseR,midR,headR,baseY,midY,headY,targetX,targetY,targetR;

        SnowmanView(Context c){
            super(c);ctx=c;density=getResources().getDisplayMetrics().density;textScale=Math.min(getResources().getDisplayMetrics().scaledDensity,density*1.18f);
            vib=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);prefs=c.getSharedPreferences("snowman_game",Context.MODE_PRIVATE);
            bestScore=prefs.getInt("best_score",0);year=Math.max(1,Math.min(7,prefs.getInt("life_year",1)));wallet=Math.max(0,prefs.getInt("coins",0));
            text.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeWidth(dp(2));
            String[] names={"Очі","Морква","Ґудзики","Шарф","Шапка","Руки"};for(int i=0;i<ACCESSORY_COUNT;i++)accessories[i]=new Accessory(i,names[i]);
            mission=rnd.nextInt(3);setClickable(true);setFocusable(true);setContentDescription("Гра Зліпи сніговика");
            setOnApplyWindowInsetsListener(new OnApplyWindowInsetsListener(){@Override public WindowInsets onApplyWindowInsets(View v,WindowInsets insets){if(Build.VERSION.SDK_INT>=30){Insets bars=insets.getInsets(WindowInsets.Type.systemBars());safeTop=bars.top;safeBottom=bars.bottom;}else{safeTop=insets.getSystemWindowInsetTop();safeBottom=insets.getSystemWindowInsetBottom();}invalidate();return insets;}});requestApplyInsets();
        }

        float dp(float v){return v*density;}float tx(float v){return v*textScale;}float clamp(float v,float a,float b){return Math.max(a,Math.min(b,v));}
        float dist(float x1,float y1,float x2,float y2){return(float)Math.hypot(x1-x2,y1-y2);}float smooth(float v){v=clamp(v,0,1);return v*v*(3-2*v);}float mix(float a,float b,float t){return a+(b-a)*t;}
        void vibrate(int ms){if(vib==null||!vib.hasVibrator())return;if(Build.VERSION.SDK_INT>=26)vib.vibrate(VibrationEffect.createOneShot(ms,85));else vib.vibrate(ms);}
        void ensureTimer(){if(startTime==0)startTime=SystemClock.elapsedRealtime();}int elapsedSeconds(){if(startTime==0)return 0;if(finished)return finishElapsed;return(int)((SystemClock.elapsedRealtime()-startTime)/1000L);}
        int avgBuild(){return balls==0?0:qualitySum/balls;}int avgDecor(){return decorPlaced==0?0:decorQualitySum/decorPlaced;}int yearGoal(){return 1100+(year-1)*320;}float effort(){return 1f+(year-1)*.20f;}
        String ageName(){switch(year){case 1:return"Малюк";case 2:return"Малюк-дослідник";case 3:return"Пустун";case 4:return"Помічник";case 5:return"Майстер снігу";case 6:return"Майбутній школяр";default:return"Школяр";}}
        String missionText(){int acc=Math.min(94,84+year);int sec=Math.max(58,94-year*4);if(mission==0)return"МІСІЯ: точність куль ≥ "+acc+"%";if(mission==1)return"МІСІЯ: завершити ≤ "+sec+" с";return"МІСІЯ: декор ≥ "+acc+"%";}

        @Override protected void onDraw(Canvas c){super.onDraw(c);layoutGame();if(sponsorScene){drawSponsorScene(c);postInvalidateOnAnimation();return;}drawBackground(c);drawHud(c);drawTip(c);drawSnowman(c);if(!finished){if(balls<3)drawRollingArea(c);else drawDecorationTray(c);}drawDust(c);if(finished)drawFinishOverlay(c);else if(startTime!=0)postInvalidateDelayed(450);}

        void layoutGame(){float w=getWidth(),h=getHeight(),bottom=h-safeBottom,usableH=Math.max(dp(420),bottom-safeTop);compact=usableH<dp(650);narrow=w<dp(360);float m=narrow?dp(9):dp(13),hudH=compact?dp(68):dp(76),tipH=compact?dp(40):dp(46),interactionH=balls<3?(compact?dp(104):dp(126)):(compact?dp(132):dp(156));hudRect.set(m,safeTop+dp(8),w-m,safeTop+dp(8)+hudH);tipRect.set(m,hudRect.bottom+dp(7),w-m,hudRect.bottom+dp(7)+tipH);interactionRect.set(m,bottom-interactionH-dp(7),w-m,bottom-dp(7));playTop=tipRect.bottom+dp(5);playBottom=interactionRect.top-dp(6);float playH=Math.max(dp(220),playBottom-playTop);baseR=clamp(Math.min(w*.205f,playH/4.02f),dp(34),dp(82));midR=baseR*.72f;headR=baseR*.54f;baseY=playBottom-baseR-dp(5);midY=baseY-(baseR+midR)*.84f;headY=midY-(midR+headR)*.84f;targetX=w/2f;if(balls==0){targetY=baseY;targetR=baseR;}else if(balls==1){targetY=midY;targetR=midR;}else{targetY=headY;targetR=headR;}setAccessoryTargets();layoutAccessorySlots();if(Float.isNaN(rollX)||Float.isNaN(rollY))resetRollingBallPosition();if(!draggingBall&&balls<3)keepRollingBallInsideZone();}
        void setAccessoryTargets(){float cx=getWidth()/2f;setTarget(EYES,cx,headY-headR*.16f);setTarget(NOSE,cx,headY+headR*.05f);setTarget(BUTTONS,cx,midY+midR*.02f);setTarget(SCARF,cx,midY-midR*.73f);setTarget(HAT,cx,headY-headR*1.28f);setTarget(ARMS,cx,midY-midR*.08f);}void setTarget(int t,float x,float y){accessories[t].targetX=x;accessories[t].targetY=y;}
        void layoutAccessorySlots(){if(balls<3)return;float gap=dp(6),pad=dp(8),sw=(interactionRect.width()-pad*2-gap*2)/3f,sh=(interactionRect.height()-pad*2-gap)/2f;for(int i=0;i<ACCESSORY_COUNT;i++){int row=i/3,col=i%3;float l=interactionRect.left+pad+col*(sw+gap),t=interactionRect.top+pad+row*(sh+gap);accessories[i].slot.set(l,t,l+sw,t+sh);}finishBtn.set(interactionRect.left+dp(28),interactionRect.top+dp(22),interactionRect.right-dp(28),interactionRect.bottom-dp(22));}
        void resetRollingBallPosition(){rollX=interactionRect.centerX();rollY=interactionRect.centerY()+dp(3);}float rollingRadius(){if(balls>=3)return 0;float s=dp(13),m=Math.min(targetR*.72f,interactionRect.height()*.36f);return s+(m-s)*clamp(rollProgress/100f,0,1);}void keepRollingBallInsideZone(){float r=Math.max(dp(13),rollingRadius());rollX=clamp(rollX,interactionRect.left+r+dp(3),interactionRect.right-r-dp(3));rollY=clamp(rollY,interactionRect.top+r+dp(3),interactionRect.bottom-r-dp(3));}

        void drawBackground(Canvas c){float w=getWidth(),h=getHeight(),bottom=h-safeBottom;LinearGradient sky=new LinearGradient(0,safeTop,0,bottom*.66f,Color.rgb(156,217,247),Color.rgb(225,246,255),Shader.TileMode.CLAMP);p.setShader(sky);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.argb(220,255,255,255));c.drawOval(new RectF(-w*.42f,bottom*.39f,w*.68f,bottom*.69f),p);p.setColor(Color.argb(238,247,252,255));c.drawOval(new RectF(w*.22f,bottom*.46f,w*1.34f,bottom*.73f),p);p.setColor(Color.rgb(239,249,254));c.drawRect(0,bottom*.62f,w,h,p);p.setColor(Color.argb(56,55,111,132));for(int i=0;i<5;i++){float x=w*(.07f+i*.235f),y=bottom*(.58f+(i%2)*.016f),s=dp(14+(i%3)*4);Path tr=new Path();tr.moveTo(x,y-s*2.3f);tr.lineTo(x-s,y);tr.lineTo(x+s,y);tr.close();c.drawPath(tr,p);}p.setColor(Color.argb(145,255,255,255));int flakes=compact?18:26;float range=Math.max(dp(120),playBottom-safeTop);for(int i=0;i<flakes;i++){float x=(i*139f+31f)%Math.max(1f,w),y=safeTop+dp(16)+((i*197f)%range);c.drawCircle(x,y,dp(1.1f+(i%3)*.45f),p);}}

        void drawHud(Canvas c){RectF r=hudRect;p.setColor(Color.argb(244,255,255,255));c.drawRoundRect(r,dp(21),dp(21),p);text.setTextAlign(Paint.Align.LEFT);text.setColor(Color.rgb(38,69,89));text.setTextSize(tx(narrow?8.5f:9.5f));c.drawText("РІК "+year+" • "+ageName(),r.left+dp(14),r.top+dp(18),text);String stage=balls<3?"КУЛЯ "+(balls+1)+"/3":"ДЕКОР "+decorPlaced+"/6";text.setTextSize(tx(narrow?13:15));c.drawText(stage,r.left+dp(14),r.top+dp(42),text);text.setTextSize(tx(7.5f));text.setColor(Color.rgb(97,132,150));c.drawText("ЦІЛЬ "+yearGoal()+" • ЗУСИЛЛЯ ×"+String.format("%.1f",effort()),r.left+dp(14),r.bottom-dp(9),text);text.setTextAlign(Paint.Align.RIGHT);text.setTextSize(tx(12));text.setColor(Color.rgb(34,104,146));c.drawText("★ "+score,r.right-dp(14),r.top+dp(23),text);text.setTextSize(tx(9));text.setColor(Color.rgb(80,128,151));c.drawText("● "+wallet+" монет",r.right-dp(14),r.top+dp(43),text);text.setTextSize(tx(7.5f));text.setColor(Color.rgb(108,139,154));c.drawText((startTime==0?"0:00":formatTime(elapsedSeconds()))+" • рек "+bestScore,r.right-dp(14),r.bottom-dp(9),text);}
        String formatTime(int sec){return String.format("%d:%02d",sec/60,sec%60);}void drawTip(Canvas c){p.setColor(Color.argb(216,234,247,254));c.drawRoundRect(tipRect,dp(17),dp(17),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(narrow?9.2f:10.3f));text.setColor(Color.rgb(43,82,108));c.drawText(tip,tipRect.centerX(),tipRect.centerY()-dp(3),text);text.setTextSize(tx(narrow?6.8f:7.8f));text.setColor(Color.rgb(92,137,159));c.drawText(missionText(),tipRect.centerX(),tipRect.centerY()+dp(12),text);}

        void drawSnowman(Canvas c){float cx=getWidth()/2f;p.setColor(Color.argb(42,68,129,157));c.drawOval(new RectF(cx-baseR*.92f,baseY+baseR*.69f,cx+baseR*.92f,baseY+baseR*1.05f),p);if(balls>=1)drawBall(c,cx,baseY,baseR,1);if(balls>=2)drawBall(c,cx,midY,midR,2);if(balls>=3)drawBall(c,cx,headY,headR,3);if(balls<3){stroke.setStrokeWidth(dp(2));stroke.setPathEffect(new DashPathEffect(new float[]{dp(7),dp(6)},0));stroke.setColor(Color.argb(ballReady?190:90,52,126,163));c.drawCircle(targetX,targetY,targetR,stroke);stroke.setPathEffect(null);if(ballReady){text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(9));text.setColor(Color.rgb(65,123,151));c.drawText("ПЕРЕТЯГНИ СЮДИ",targetX,targetY,text);}}for(Accessory a:accessories)if(a.placed)drawAccessory(c,a.type,a.x,a.y,255);if(draggingAccessory>=0){Accessory a=accessories[draggingAccessory];stroke.setColor(Color.argb(180,46,126,164));stroke.setStrokeWidth(dp(2));stroke.setPathEffect(new DashPathEffect(new float[]{dp(6),dp(5)},0));c.drawCircle(a.targetX,a.targetY,tolerance(a.type)*.52f,stroke);stroke.setPathEffect(null);drawAccessory(c,a.type,dragAccessoryX,dragAccessoryY,235);}}
        void drawBall(Canvas c,float x,float y,float r,int seed){RadialGradient g=new RadialGradient(x-r*.31f,y-r*.37f,r*1.42f,new int[]{Color.WHITE,Color.rgb(247,252,255),Color.rgb(198,227,242)},new float[]{0,.57f,1},Shader.TileMode.CLAMP);p.setShader(g);c.drawCircle(x,y,r,p);p.setShader(null);stroke.setColor(Color.argb(82,101,162,193));stroke.setStrokeWidth(dp(1));c.drawCircle(x,y,r-dp(.5f),stroke);p.setColor(Color.argb(55,136,186,210));for(int i=0;i<7;i++){double a=i*2.22+seed*.8;float rr=r*(.23f+((i*31+seed*17)%49)/100f);c.drawCircle(x+(float)Math.cos(a)*rr,y+(float)Math.sin(a)*rr,Math.max(dp(.8f),r*.018f),p);}p.setColor(Color.argb(170,255,255,255));c.drawOval(new RectF(x-r*.52f,y-r*.58f,x-r*.08f,y-r*.28f),p);}

        void drawRollingArea(Canvas c){RectF r=interactionRect;p.setColor(Color.argb(224,251,254,255));c.drawRoundRect(r,dp(23),dp(23),p);stroke.setStrokeWidth(dp(1.3f));stroke.setColor(Color.argb(105,111,177,208));c.drawRoundRect(new RectF(r.left+dp(1),r.top+dp(1),r.right-dp(1),r.bottom-dp(1)),dp(22),dp(22),stroke);for(int i=0;i<5;i++){float yy=r.top+r.height()*(.23f+i*.14f);p.setColor(Color.argb(38,84,153,184));c.drawRoundRect(new RectF(r.left+dp(18),yy,r.right-dp(18),yy+dp(1.2f)),dp(1),dp(1),p);}drawRollingBall(c,rollX,rollY,rollingRadius());text.setTextAlign(Paint.Align.LEFT);text.setTextSize(tx(8.5f));text.setColor(Color.rgb(96,151,177));c.drawText(ballReady?"КУЛЯ ГОТОВА":"КОТИ ПАЛЬЦЕМ • "+(int)rollProgress+"%",r.left+dp(12),r.top+dp(17),text);}
        void drawRollingBall(Canvas c,float x,float y,float r){RadialGradient g=new RadialGradient(x-r*.32f,y-r*.38f,r*1.45f,new int[]{Color.WHITE,Color.rgb(244,251,255),Color.rgb(190,224,240)},new float[]{0,.56f,1},Shader.TileMode.CLAMP);p.setShader(g);c.drawCircle(x,y,r,p);p.setShader(null);stroke.setColor(Color.argb(90,91,153,184));stroke.setStrokeWidth(dp(1));c.drawCircle(x,y,r-dp(.5f),stroke);}

        void drawDecorationTray(Canvas c){RectF r=interactionRect;p.setColor(Color.argb(226,250,254,255));c.drawRoundRect(r,dp(23),dp(23),p);if(decorPlaced==ACCESSORY_COUNT){p.setColor(Color.rgb(38,105,145));c.drawRoundRect(finishBtn,dp(20),dp(20),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(12));text.setColor(Color.WHITE);c.drawText("ЗАВЕРШИТИ СНІГОВИКА",finishBtn.centerX(),finishBtn.centerY()+dp(4),text);return;}for(Accessory a:accessories){RectF s=a.slot;p.setColor(a.placed?Color.rgb(226,242,235):Color.WHITE);c.drawRoundRect(s,dp(15),dp(15),p);if(a.placed){text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(12));text.setColor(Color.rgb(69,141,116));c.drawText("✓",s.centerX(),s.centerY(),text);}else drawTrayIcon(c,a.type,s.centerX(),s.centerY()-dp(5),Math.min(s.width(),s.height())*.27f);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(narrow?6.5f:7.5f));text.setColor(Color.rgb(84,128,151));c.drawText(a.name,s.centerX(),s.bottom-dp(7),text);}}
        void drawTrayIcon(Canvas c,int type,float x,float y,float s){p.setColor(Color.rgb(48,70,83));if(type==EYES){c.drawCircle(x-s*.34f,y,s*.18f,p);c.drawCircle(x+s*.34f,y,s*.18f,p);}else if(type==NOSE){Path n=new Path();n.moveTo(x-s*.28f,y-s*.15f);n.lineTo(x+s*.70f,y);n.lineTo(x-s*.28f,y+s*.15f);n.close();p.setColor(Color.rgb(242,119,37));c.drawPath(n,p);}else if(type==BUTTONS){for(int i=-1;i<=1;i++)c.drawCircle(x,y+i*s*.43f,s*.13f,p);}else if(type==SCARF){p.setColor(Color.rgb(198,62,68));c.drawRoundRect(new RectF(x-s*.72f,y-s*.17f,x+s*.72f,y+s*.17f),dp(3),dp(3),p);}else if(type==HAT){p.setColor(Color.rgb(45,62,78));c.drawRect(x-s*.72f,y+s*.18f,x+s*.72f,y+s*.36f,p);c.drawRoundRect(new RectF(x-s*.42f,y-s*.58f,x+s*.42f,y+s*.20f),dp(4),dp(4),p);}else{stroke.setColor(Color.rgb(111,82,58));stroke.setStrokeWidth(dp(3));c.drawLine(x-s*.75f,y+s*.30f,x-s*.15f,y-s*.20f,stroke);c.drawLine(x+s*.75f,y+s*.30f,x+s*.15f,y-s*.20f,stroke);}}
        float tolerance(int type){float mul=Math.max(.72f,1f-(year-1)*.035f);if(type==HAT)return headR*.95f*mul;if(type==ARMS||type==SCARF||type==BUTTONS)return midR*.90f*mul;return headR*.80f*mul;}
        void drawAccessory(Canvas c,int type,float x,float y,int alpha){if(type==EYES){p.setColor(Color.argb(alpha,40,54,64));c.drawCircle(x-headR*.29f,y,headR*.075f,p);c.drawCircle(x+headR*.29f,y,headR*.075f,p);}else if(type==NOSE){Path n=new Path();n.moveTo(x-headR*.05f,y-headR*.09f);n.lineTo(x+headR*.78f,y+headR*.04f);n.lineTo(x-headR*.05f,y+headR*.12f);n.close();p.setColor(Color.argb(alpha,244,118,35));c.drawPath(n,p);}else if(type==BUTTONS){p.setColor(Color.argb(alpha,48,63,73));for(int i=-1;i<=1;i++)c.drawCircle(x,y+i*midR*.38f,midR*.055f,p);}else if(type==SCARF){p.setColor(Color.argb(alpha,200,61,68));c.drawRoundRect(new RectF(x-midR*.84f,y-midR*.10f,x+midR*.84f,y+midR*.12f),dp(7),dp(7),p);c.drawRoundRect(new RectF(x+midR*.34f,y+midR*.02f,x+midR*.60f,y+midR*.80f),dp(6),dp(6),p);}else if(type==HAT){p.setColor(Color.argb(alpha,45,62,78));c.drawRoundRect(new RectF(x-headR*.75f,y-headR*.02f,x+headR*.75f,y+headR*.17f),dp(5),dp(5),p);c.drawRoundRect(new RectF(x-headR*.50f,y-headR*.70f,x+headR*.50f,y+headR*.04f),dp(8),dp(8),p);}else{stroke.setColor(Color.argb(alpha,108,80,58));stroke.setStrokeWidth(Math.max(dp(3),baseR*.035f));stroke.setStrokeCap(Paint.Cap.ROUND);c.drawLine(x-midR*.65f,y,x-midR*1.55f,y-midR*.48f,stroke);c.drawLine(x+midR*.65f,y,x+midR*1.55f,y-midR*.48f,stroke);stroke.setStrokeCap(Paint.Cap.BUTT);}}

        void addDust(float x,float y,float d){if(dust.size()>42)dust.remove(0);dust.add(new Dust(x+rnd.nextFloat()*dp(11)-dp(5.5f),y+rnd.nextFloat()*dp(9)-dp(4.5f),dp(2)+Math.min(dp(4.5f),d*.018f),205));}void drawDust(Canvas c){Iterator<Dust>it=dust.iterator();boolean more=false;while(it.hasNext()){Dust d=it.next();d.alpha-=15;d.radius+=dp(.08f);if(d.alpha<=0){it.remove();continue;}more=true;p.setColor(Color.argb(d.alpha,255,255,255));c.drawCircle(d.x,d.y,d.radius,p);}if(more)postInvalidateOnAnimation();}

        @Override public boolean onTouchEvent(MotionEvent e){float x=e.getX(),y=e.getY();if(sponsorScene){if(e.getAction()==MotionEvent.ACTION_UP){performClick();float t=(SystemClock.elapsedRealtime()-sponsorStart)/1000f;if(t>5.5f&&sponsorCloseBtn.contains(x,y)){sponsorScene=false;invalidate();}}return true;}if(e.getAction()==MotionEvent.ACTION_DOWN){lastX=x;lastY=y;lastDx=0;lastDy=0;if(finished)return true;if(balls<3){float rr=rollingRadius();if(ballReady&&dist(x,y,rollX,rollY)<=rr*1.55f+dp(10)){ensureTimer();draggingBall=true;rolling=false;tip="Перетягни кулю в пунктирний контур";return true;}if(!ballReady&&interactionRect.contains(x,y)){ensureTimer();rolling=true;draggingBall=false;rollX=x;rollY=y;keepRollingBallInsideZone();return true;}}else if(decorPlaced<ACCESSORY_COUNT){for(Accessory a:accessories)if(!a.placed&&a.slot.contains(x,y)){ensureTimer();draggingAccessory=a.type;dragAccessoryX=x;dragAccessoryY=y;tip="Перетягни «"+a.name+"» на сніговика";invalidate();return true;}}return true;}if(e.getAction()==MotionEvent.ACTION_MOVE){if(finished)return true;if(rolling&&!ballReady&&balls<3){float dx=x-lastX,dy=y-lastY,d=(float)Math.hypot(dx,dy);if(d>dp(1.2f)){float required=(dp(350)+targetR*1.55f)*effort();rollProgress=Math.min(100,rollProgress+d/required*100);if(lastDx!=0||lastDy!=0){float a=(float)Math.hypot(lastDx,lastDy),cos=(lastDx*dx+lastDy*dy)/Math.max(.001f,a*d);if(cos<-.45f)turnPenalty+=1;}lastDx=dx;lastDy=dy;rollX=x;rollY=y;keepRollingBallInsideZone();addDust(rollX,rollY,d);if(rollProgress>=100){rollProgress=100;ballReady=true;rolling=false;tip="Куля готова — постав її в контур";vibrate(26);}else tip="Коти кулю: "+(int)rollProgress+"%";lastX=x;lastY=y;invalidate();}return true;}if(draggingBall&&ballReady&&balls<3){rollX=clamp(x,dp(8),getWidth()-dp(8));rollY=clamp(y,playTop,interactionRect.bottom);addDust(rollX,rollY,dp(3));invalidate();return true;}if(draggingAccessory>=0){dragAccessoryX=clamp(x,dp(6),getWidth()-dp(6));dragAccessoryY=clamp(y,playTop-dp(35),interactionRect.bottom);invalidate();return true;}return true;}if(e.getAction()==MotionEvent.ACTION_UP||e.getAction()==MotionEvent.ACTION_CANCEL){performClick();if(finished){if(sponsorBtn.contains(x,y)&&!sponsorRewarded){sponsorScene=true;sponsorStart=SystemClock.elapsedRealtime();vibrate(20);invalidate();return true;}if(stationBtn.contains(x,y)){ctx.startActivity(new Intent(ctx,JourneyActivity.class));((Activity)ctx).finish();return true;}if(replayBtn.contains(x,y)){reset();return true;}return true;}if(draggingBall&&ballReady&&balls<3){draggingBall=false;tryPlaceBall();return true;}rolling=false;if(draggingAccessory>=0){int type=draggingAccessory;draggingAccessory=-1;tryPlaceAccessory(type,x,y);return true;}if(balls>=3&&decorPlaced==ACCESSORY_COUNT&&finishBtn.contains(x,y)){finishGame();return true;}return true;}return true;}
        @Override public boolean performClick(){super.performClick();return true;}

        void tryPlaceBall(){float d=dist(rollX,rollY,targetX,targetY),threshold=targetR*.90f+rollingRadius()*.30f;if(d<=threshold){float acc=clamp(1-d/Math.max(dp(1),threshold),0,1);int q=Math.max(55,Math.min(100,Math.round(72+acc*28-Math.min(10,turnPenalty*.5f))));qualitySum+=q;score+=100+Math.round(acc*100);if(q>=90){combo++;score+=20*combo;maxCombo=Math.max(maxCombo,combo);}else combo=0;balls++;vibrate(38);rollProgress=0;ballReady=false;turnPenalty=0;resetRollingBallPosition();tip=balls<3?"Точність "+q+"%. Куля "+(balls+1)+" буде важчою":"Каркас готовий — додай деталі";invalidate();}else{tip="Не попав у контур — постав точніше";resetRollingBallPosition();vibrate(14);invalidate();}}
        void tryPlaceAccessory(int type,float x,float y){Accessory a=accessories[type];float tol=tolerance(type),d=dist(x,y,a.targetX,a.targetY);if(d<=tol){float acc=clamp(1-d/Math.max(dp(1),tol),0,1);int q=Math.max(50,Math.min(100,Math.round(58+acc*42)));a.placed=true;a.x=x;a.y=y;a.quality=q;decorPlaced++;decorQualitySum+=q;score+=70+q;if(q>=90){combo++;score+=combo*20;maxCombo=Math.max(maxCombo,combo);}else combo=0;vibrate(24);tip=decorPlaced<ACCESSORY_COUNT?a.name+": "+q+"%. Наступна деталь":"Декор готовий — заверши сніговика";}else{combo=0;tip="Занадто далеко — спробуй поставити точніше";vibrate(12);}invalidate();}
        void finishGame(){ensureTimer();finishElapsed=elapsedSeconds();score+=Math.max(0,180-finishElapsed*2);int acc=Math.min(94,84+year),sec=Math.max(58,94-year*4);if(mission==0)missionSuccess=avgBuild()>=acc;else if(mission==1)missionSuccess=finishElapsed<=sec;else missionSuccess=avgDecor()>=acc;if(missionSuccess)score+=250;finished=true;if(!coinsAwarded){runCoins=Math.max(1,score/300);wallet+=runCoins;coinsAwarded=true;prefs.edit().putInt("coins",wallet).apply();}if(score>bestScore){bestScore=score;prefs.edit().putInt("best_score",bestScore).apply();}vibrate(65);invalidate();}

        void drawFinishOverlay(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;p.setColor(Color.argb(194,20,43,59));c.drawRect(0,0,getWidth(),getHeight(),p);float cw=Math.min(w-dp(22),dp(390)),ch=Math.min(bottom-safeTop-dp(18),compact?dp(480):dp(525)),l=(w-cw)/2,top=safeTop+(bottom-safeTop-ch)/2;RectF card=new RectF(l,top,l+cw,top+ch);p.setColor(Color.WHITE);c.drawRoundRect(card,dp(28),dp(28),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(17));text.setColor(Color.rgb(30,69,93));c.drawText("Рік "+year+" завершено",card.centerX(),card.top+dp(36),text);text.setTextSize(tx(34));text.setColor(Color.rgb(39,117,159));c.drawText(String.valueOf(score),card.centerX(),card.top+dp(82),text);text.setTextSize(tx(8.5f));text.setColor(Color.rgb(103,137,155));c.drawText("ЦІЛЬ "+yearGoal()+" • "+(score>=yearGoal()?"ВИКОНАНО":"ЩЕ Є КУДИ РОСТИ"),card.centerX(),card.top+dp(105),text);c.drawText("КУЛІ "+avgBuild()+"%   •   ДЕКОР "+avgDecor()+"%   •   "+formatTime(finishElapsed),card.centerX(),card.top+dp(128),text);RectF coin=new RectF(card.left+dp(24),card.top+dp(145),card.right-dp(24),card.top+dp(195));p.setColor(Color.rgb(235,247,239));c.drawRoundRect(coin,dp(17),dp(17),p);text.setTextSize(tx(10));text.setColor(Color.rgb(55,126,99));c.drawText("ЗАРОБЛЕНО +"+runCoins+" МОНЕТ   •   БАЛАНС "+wallet,coin.centerX(),coin.centerY()+dp(4),text);RectF badge=new RectF(card.left+dp(24),card.top+dp(207),card.right-dp(24),card.top+dp(252));p.setColor(missionSuccess?Color.rgb(229,246,237):Color.rgb(246,239,232));c.drawRoundRect(badge,dp(15),dp(15),p);text.setTextSize(tx(8));text.setColor(missionSuccess?Color.rgb(55,130,104):Color.rgb(145,106,72));c.drawText(missionSuccess?"МІСІЮ ВИКОНАНО +250":"МІСІЮ НЕ ВИКОНАНО",badge.centerX(),badge.centerY()+dp(3),text);
            sponsorBtn.set(card.left+dp(22),card.bottom-dp(178),card.right-dp(22),card.bottom-dp(128));p.setColor(sponsorRewarded?Color.rgb(188,190,193):Color.rgb(226,91,122));c.drawRoundRect(sponsorBtn,dp(18),dp(18),p);text.setTextSize(tx(10));text.setColor(Color.WHITE);c.drawText(sponsorRewarded?"ЕСКІМОС УЖЕ СКУШТОВАНО":"СПРОБУВАТИ ЕСКІМОС +150",sponsorBtn.centerX(),sponsorBtn.centerY()+dp(3),text);
            stationBtn.set(card.left+dp(22),card.bottom-dp(116),card.right-dp(22),card.bottom-dp(62));p.setColor(Color.rgb(35,106,153));c.drawRoundRect(stationBtn,dp(19),dp(19),p);text.setTextSize(tx(11));text.setColor(Color.WHITE);c.drawText(year>=7?"ДО ШКІЛЬНИХ ПРИГОД":"НА ВОКЗАЛ • У РІК "+(year+1),stationBtn.centerX(),stationBtn.centerY()+dp(4),text);
            replayBtn.set(card.left+dp(45),card.bottom-dp(51),card.right-dp(45),card.bottom-dp(12));p.setColor(Color.rgb(238,246,250));c.drawRoundRect(replayBtn,dp(16),dp(16),p);text.setTextSize(tx(8.5f));text.setColor(Color.rgb(76,118,142));c.drawText("ЩЕ РАЗ У ЦЬОМУ РОЦІ",replayBtn.centerX(),replayBtn.centerY()+dp(3),text);
        }

        void drawSponsorScene(Canvas c){float w=getWidth(),h=getHeight(),bottom=h-safeBottom,t=(SystemClock.elapsedRealtime()-sponsorStart)/1000f;LinearGradient sky=new LinearGradient(0,0,0,bottom*.75f,Color.rgb(168,224,249),Color.rgb(232,248,255),Shader.TileMode.CLAMP);p.setShader(sky);c.drawRect(0,0,w,h,p);p.setShader(null);p.setColor(Color.rgb(242,250,255));c.drawRect(0,bottom*.64f,w,h,p);RectF poster=new RectF(dp(16),safeTop+dp(15),w-dp(16),safeTop+dp(132));p.setColor(Color.argb(240,255,255,255));c.drawRoundRect(poster,dp(24),dp(24),p);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(tx(6.5f));text.setColor(Color.rgb(112,140,154));c.drawText("ДЕМО-ІНТЕГРАЦІЯ",poster.left+dp(16),poster.top+dp(19),text);text.setTextSize(tx(25));text.setColor(Color.rgb(214,72,111));c.drawText("ЕСКІМОС",poster.left+dp(16),poster.top+dp(55),text);text.setTextSize(tx(9));text.setColor(Color.rgb(62,101,122));c.drawText("Холодне до холодного.",poster.left+dp(16),poster.top+dp(82),text);float cx=w*.46f,br=Math.min(w*.18f,dp(70)),mr=br*.72f,hr=br*.54f,by=bottom-dp(115)-br,my=by-(br+mr)*.84f,hy=my-(mr+hr)*.84f;drawBall(c,cx,by,br,10);drawBall(c,cx,my,mr,11);drawBall(c,cx,hy,hr,12);p.setColor(Color.rgb(43,57,66));c.drawCircle(cx-hr*.28f,hy-hr*.15f,hr*.078f,p);c.drawCircle(cx+hr*.28f,hy-hr*.15f,hr*.078f,p);Path nose=new Path();nose.moveTo(cx-hr*.04f,hy-hr*.03f);nose.lineTo(cx+hr*.72f,hy+hr*.08f);nose.lineTo(cx-hr*.04f,hy+hr*.14f);nose.close();p.setColor(Color.rgb(241,117,34));c.drawPath(nose,p);float appear=smooth((t-.2f)/.9f),take=smooth((t-1f)/1.4f),eat=smooth((t-2.5f)/2.6f);float ix=mix(w+dp(35),cx+mr*1.4f,appear),iy=mix(h*.58f,my,appear);ix=mix(ix,cx+hr*.58f,take);iy=mix(iy,hy+hr*.32f,take);float scoop=Math.max(.32f,1-.66f*eat);stroke.setColor(Color.rgb(105,78,56));stroke.setStrokeWidth(dp(3));stroke.setStrokeCap(Paint.Cap.ROUND);c.drawLine(cx-mr*.62f,my,cx-mr*.18f+(ix-cx)*.72f,iy+dp(15),stroke);c.drawLine(cx+mr*.62f,my,cx+mr*.18f+(ix-cx)*.72f,iy+dp(15),stroke);stroke.setStrokeCap(Paint.Cap.BUTT);drawIceCream(c,ix,iy,scoop);if(t>4.9f&&!sponsorRewarded){sponsorRewarded=true;score+=150;if(score>bestScore){bestScore=score;prefs.edit().putInt("best_score",bestScore).apply();}vibrate(45);}if(t>4.7f){text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(17));text.setColor(Color.rgb(42,93,121));c.drawText("Сніговик ласує! +150",w/2,safeTop+dp(172),text);}if(t>5.5f){float bw=Math.min(w-dp(38),dp(338)),bh=dp(54),l=(w-bw)/2,top=bottom-dp(70);sponsorCloseBtn.set(l,top,l+bw,top+bh);p.setColor(Color.rgb(38,105,145));c.drawRoundRect(sponsorCloseBtn,dp(18),dp(18),p);text.setTextSize(tx(10));text.setColor(Color.WHITE);c.drawText("ПОВЕРНУТИСЯ ДО РЕЗУЛЬТАТУ",sponsorCloseBtn.centerX(),sponsorCloseBtn.centerY()+dp(4),text);}}
        void drawIceCream(Canvas c,float x,float y,float scale){float ch=dp(52),cw=dp(31),r=dp(22)*scale;Path cone=new Path();cone.moveTo(x-cw/2,y+dp(10));cone.lineTo(x+cw/2,y+dp(10));cone.lineTo(x,y+ch);cone.close();p.setColor(Color.rgb(211,151,80));c.drawPath(cone,p);p.setColor(Color.rgb(247,136,169));c.drawCircle(x,y,r,p);p.setColor(Color.argb(165,255,255,255));c.drawCircle(x-r*.32f,y-r*.34f,r*.28f,p);p.setColor(Color.WHITE);c.drawRoundRect(new RectF(x-dp(20),y+dp(27),x+dp(20),y+dp(41)),dp(5),dp(5),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(5.5f));text.setColor(Color.rgb(201,70,105));c.drawText("ЕСКІМОС",x,y+dp(37),text);}

        void reset(){balls=0;score=0;qualitySum=0;decorQualitySum=0;decorPlaced=0;combo=0;maxCombo=0;finished=false;sponsorScene=false;sponsorRewarded=false;coinsAwarded=false;runCoins=0;rollProgress=0;rolling=false;draggingBall=false;ballReady=false;turnPenalty=0;draggingAccessory=-1;startTime=0;finishElapsed=0;missionSuccess=false;mission=rnd.nextInt(3);tip="Коти сніг пальцем — зроби першу кулю";dust.clear();for(Accessory a:accessories){a.placed=false;a.quality=0;a.x=a.y=0;}rollX=Float.NaN;rollY=Float.NaN;vibrate(18);invalidate();}
        static class Accessory{final int type;final String name;final RectF slot=new RectF();float targetX,targetY,x,y;int quality;boolean placed;Accessory(int t,String n){type=t;name=n;}}static class Dust{float x,y,radius;int alpha;Dust(float x,float y,float r,int a){this.x=x;this.y=y;radius=r;alpha=a;}}
    }
}
