package com.snowmangame;

import android.app.Activity;
import android.content.Context;
import android.content.Intent;
import android.content.SharedPreferences;
import android.graphics.*;
import android.os.Build;
import android.os.Bundle;
import android.os.VibrationEffect;
import android.os.Vibrator;
import android.view.MotionEvent;
import android.view.View;
import android.view.Window;
import android.view.WindowInsets;

public class SchoolActivity extends Activity {
    @Override public void onCreate(Bundle b){
        super.onCreate(b);
        Window w=getWindow();
        if(Build.VERSION.SDK_INT>=21){w.setStatusBarColor(Color.TRANSPARENT);w.setNavigationBarColor(Color.rgb(236,247,252));int flags=View.SYSTEM_UI_FLAG_LIGHT_STATUS_BAR;if(Build.VERSION.SDK_INT>=26)flags|=View.SYSTEM_UI_FLAG_LIGHT_NAVIGATION_BAR;w.getDecorView().setSystemUiVisibility(flags);}
        if(Build.VERSION.SDK_INT>=29)w.setNavigationBarContrastEnforced(false);
        setContentView(new SchoolView(this));
    }
    static class SchoolView extends View {
        static final int GATE=0,CLASS_DOOR=1,DESK=2,LESSON=3,DONE=4;
        final Context ctx; final SharedPreferences prefs; final Paint p=new Paint(Paint.ANTI_ALIAS_FLAG),text=new Paint(Paint.ANTI_ALIAS_FLAG),stroke=new Paint(Paint.ANTI_ALIAS_FLAG);
        final RectF action=new RectF(),memoryBtn=new RectF(),wardrobeBtn=new RectF(); final RectF[] doors={new RectF(),new RectF(),new RectF()},desks={new RectF(),new RectF(),new RectF()},answers={new RectF(),new RectF(),new RectF()};
        final float density,textScale; final Vibrator vibrator; float safeTop,safeBottom; int stage,mistakes; String feedback="";
        SchoolView(Context c){super(c);ctx=c;prefs=c.getSharedPreferences("snowman_game",Context.MODE_PRIVATE);density=getResources().getDisplayMetrics().density;textScale=Math.min(getResources().getDisplayMetrics().scaledDensity,density*1.15f);vibrator=(Vibrator)c.getSystemService(Context.VIBRATOR_SERVICE);stage=prefs.getBoolean("school_first_day_complete",false)?DONE:Math.max(GATE,Math.min(LESSON,prefs.getInt("school_stage",GATE)));mistakes=Math.max(0,prefs.getInt("school_mistakes",0));prefs.edit().putBoolean("school_unlocked",true).apply();SnowmanStyle.ensureUnlocked(prefs,7);text.setTypeface(Typeface.create(Typeface.DEFAULT,Typeface.BOLD));stroke.setStyle(Paint.Style.STROKE);stroke.setStrokeCap(Paint.Cap.ROUND);setClickable(true);setFocusable(true);setOnApplyWindowInsetsListener(new OnApplyWindowInsetsListener(){@Override public WindowInsets onApplyWindowInsets(View v,WindowInsets i){safeTop=i.getSystemWindowInsetTop();safeBottom=i.getSystemWindowInsetBottom();invalidate();return i;}});requestApplyInsets();}
        float dp(float v){return v*density;} float tx(float v){return v*textScale;} void buzz(int ms){if(vibrator==null||!vibrator.hasVibrator())return;if(Build.VERSION.SDK_INT>=26)vibrator.vibrate(VibrationEffect.createOneShot(ms,80));else vibrator.vibrate(ms);} void next(int s){stage=s;feedback="";prefs.edit().putInt("school_stage",Math.min(s,LESSON)).apply();buzz(24);invalidate();}
        int currentGrade(){return Math.max(2,Math.min(11,prefs.getInt("school_grade",2)));}
        @Override protected void onDraw(Canvas c){super.onDraw(c);float w=getWidth(),bottom=getHeight()-safeBottom;p.setColor(Color.rgb(239,234,211));c.drawRect(0,0,w,getHeight(),p);RectF head=new RectF(dp(14),safeTop+dp(10),w-dp(14),safeTop+dp(118));p.setColor(Color.WHITE);c.drawRoundRect(head,dp(24),dp(24),p);text.setTextAlign(Paint.Align.LEFT);text.setTextSize(tx(7));text.setColor(Color.rgb(91,121,136));c.drawText("ШКОЛА • ТЕРНОПІЛЬЩИНА",head.left+dp(17),head.top+dp(22),text);text.setTextSize(tx(18));text.setColor(Color.rgb(37,73,94));c.drawText(stage==DONE?"Школа відкрита":stage==GATE?"Перший день":stage==CLASS_DOOR?"Знайди 1-А":stage==DESK?"Знайди свою парту":"Перший урок",head.left+dp(17),head.top+dp(57),text);text.setTextSize(tx(8));text.setColor(Color.rgb(91,124,141));c.drawText(stage==DONE?"Вступ пройдено • далі твій поточний клас":"Це вступ до шкільного життя",head.left+dp(17),head.top+dp(88),text);if(stage==DONE)drawDone(c);else if(stage==GATE)drawGate(c);else if(stage==CLASS_DOOR)drawDoors(c);else if(stage==DESK)drawDesks(c);else drawLesson(c);}
        void drawGate(Canvas c){float w=getWidth();text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(16));text.setColor(Color.rgb(41,105,139));c.drawText("ПЕРШИЙ ДЕНЬ У ШКОЛІ",w/2,safeTop+dp(210),text);text.setTextSize(tx(9));c.drawText("Ця сцена проходиться один раз.",w/2,safeTop+dp(250),text);button(c,"УВІЙТИ ДО ШКОЛИ");}
        void drawDoors(Canvas c){float w=getWidth(),top=safeTop+dp(200),gap=dp(12),left=dp(20),dw=(w-dp(40)-gap*2)/3f;String[] labels={"1-Б","1-А","2-А"};for(int i=0;i<3;i++){doors[i].set(left+i*(dw+gap),top,left+i*(dw+gap)+dw,top+dp(280));p.setColor(Color.rgb(119,83,59));c.drawRoundRect(doors[i],dp(8),dp(8),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(14));text.setColor(Color.WHITE);c.drawText(labels[i],doors[i].centerX(),doors[i].top+dp(45),text);}}
        void drawDesks(Canvas c){float w=getWidth(),top=safeTop+dp(220),gap=dp(14),left=dp(22),dw=(w-dp(44)-gap*2)/3f;for(int i=0;i<3;i++){desks[i].set(left+i*(dw+gap),top,left+i*(dw+gap)+dw,top+dp(180));p.setColor(Color.rgb(174,126,78));c.drawRoundRect(desks[i],dp(8),dp(8),p);if(i==1){text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(20));text.setColor(Color.WHITE);c.drawText("❄",desks[i].centerX(),desks[i].centerY(),text);}}}
        void drawLesson(Canvas c){float w=getWidth(),top=safeTop+dp(220),gap=dp(12),left=dp(24),aw=(w-dp(48)-gap*2)/3f;String[] a={"ЛІД","ВОДА","ПІСОК"};text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(14));text.setColor(Color.rgb(48,82,99));c.drawText("Що стане зі снігом у теплі?",w/2,safeTop+dp(180),text);for(int i=0;i<3;i++){answers[i].set(left+i*(aw+gap),top,left+i*(aw+gap)+aw,top+dp(140));p.setColor(Color.WHITE);c.drawRoundRect(answers[i],dp(20),dp(20),p);text.setTextSize(tx(11));text.setColor(Color.rgb(45,97,124));c.drawText(a[i],answers[i].centerX(),answers[i].centerY(),text);}}
        void drawDone(Canvas c){float w=getWidth(),bottom=getHeight()-safeBottom;RectF card=new RectF(dp(20),safeTop+dp(145),w-dp(20),bottom-dp(190));p.setColor(Color.WHITE);c.drawRoundRect(card,dp(26),dp(26),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(7));text.setColor(Color.rgb(111,131,137));c.drawText("ВСТУП ДО ШКОЛИ ЗАВЕРШЕНО",card.centerX(),card.top+dp(30),text);text.setTextSize(tx(22));text.setColor(Color.rgb(41,105,139));c.drawText("ТИ ВЖЕ У "+currentGrade()+"-МУ КЛАСІ",card.centerX(),card.top+dp(72),text);text.setTextSize(tx(9));text.setColor(Color.rgb(91,123,138));c.drawText("Не повторюємо перший клас — продовжуємо історію.",card.centerX(),card.top+dp(108),text);float gap=dp(8),half=(w-dp(48)-gap)/2f;memoryBtn.set(dp(20),bottom-dp(174),dp(20)+half,bottom-dp(121));wardrobeBtn.set(memoryBtn.right+gap,bottom-dp(174),w-dp(20),bottom-dp(121));p.setColor(Color.rgb(232,242,237));c.drawRoundRect(memoryBtn,dp(17),dp(17),p);p.setColor(Color.rgb(234,242,247));c.drawRoundRect(wardrobeBtn,dp(17),dp(17),p);text.setTextSize(tx(8));text.setColor(Color.rgb(58,106,91));c.drawText("СПОГАДИ",memoryBtn.centerX(),memoryBtn.centerY()+dp(3),text);text.setColor(Color.rgb(61,103,127));c.drawText("ГАРДЕРОБ",wardrobeBtn.centerX(),wardrobeBtn.centerY()+dp(3),text);button(c,"ПРОДОВЖИТИ "+currentGrade()+"-Й КЛАС");}
        void button(Canvas c,String label){float w=getWidth(),bottom=getHeight()-safeBottom;action.set(dp(22),bottom-dp(66),w-dp(22),bottom-dp(11));p.setColor(Color.rgb(37,108,153));c.drawRoundRect(action,dp(20),dp(20),p);text.setTextAlign(Paint.Align.CENTER);text.setTextSize(tx(9.4f));text.setColor(Color.WHITE);c.drawText(label,action.centerX(),action.centerY()+dp(4),text);}
        void completeLesson(){int days=Math.max(0,prefs.getInt("school_days",0))+1;prefs.edit().putBoolean("school_first_day_complete",true).putBoolean("school_unlocked",true).putInt("school_days",days).putInt("school_stage",DONE).apply();stage=DONE;feedback="";buzz(45);invalidate();}
        @Override public boolean onTouchEvent(MotionEvent e){if(e.getAction()!=MotionEvent.ACTION_UP)return true;performClick();float x=e.getX(),y=e.getY();if(stage==GATE&&action.contains(x,y)){next(CLASS_DOOR);return true;}if(stage==CLASS_DOOR){for(int i=0;i<3;i++)if(doors[i].contains(x,y)){if(i==1)next(DESK);else{mistakes++;buzz(12);}invalidate();return true;}}if(stage==DESK){for(int i=0;i<3;i++)if(desks[i].contains(x,y)){if(i==1)next(LESSON);else{mistakes++;buzz(12);}invalidate();return true;}}if(stage==LESSON){for(int i=0;i<3;i++)if(answers[i].contains(x,y)){if(i==1)completeLesson();else{mistakes++;buzz(12);}invalidate();return true;}}if(stage==DONE){if(memoryBtn.contains(x,y)){ctx.startActivity(new Intent(ctx,MemoryActivity.class));return true;}if(wardrobeBtn.contains(x,y)){ctx.startActivity(new Intent(ctx,WardrobeActivity.class));return true;}if(action.contains(x,y)){ctx.startActivity(new Intent(ctx,IntegratedSchoolWeekActivity.class));((Activity)ctx).finish();return true;}}return true;}
        @Override public boolean performClick(){super.performClick();return true;}
    }
}
