from pathlib import Path
import re

school_path=Path("app/src/main/java/com/snowmangame/SchoolWeekActivity.java")
gradle_path=Path("app/build.gradle")
s=school_path.read_text(encoding="utf-8")

def rep(old,new,label):
    global s
    if old not in s:
        raise SystemExit(f"v18.6 phone/swim patch failed: {label}")
    s=s.replace(old,new,1)

rep('        static final int MORNING=10,LESSON1=11,BREAK=12,LESSON2=13,HOME=14,DINNER=15;\n        static final int WEEKEND=20,WEEKEND_MINI=21,DONE=30,YEAR_DONE=31,BONUS=40,INTRO=50;','        static final int MORNING=10,LESSON1=11,BREAK=12,LESSON2=13,HOME=14,DINNER=15,CALL=16,CALL_TALK=17;\n        static final int WEEKEND=20,WEEKEND_MINI=21,DONE=30,YEAR_DONE=31,BONUS=40,INTRO=50;',"stage constants")
rep('        final RectF action=new RectF(),memoryBtn=new RectF(),wardrobeBtn=new RectF(),target=new RectF(),dishRect=new RectF();','        final RectF action=new RectF(),memoryBtn=new RectF(),wardrobeBtn=new RectF(),target=new RectF(),dishRect=new RectF();\n        final RectF acceptBtn=new RectF(),declineBtn=new RectF(),swimColdBtn=new RectF(),swimStrokeBtn=new RectF();',"interaction rects")
rep('        int bagMask,miniHits,homeStep,dinnerBites;\n        boolean yearIntro,yearComplete;\n        String feedback="",weekendChoice="";','        int bagMask,miniHits,homeStep,dinnerBites,swimLaps,swimWarmth;\n        boolean yearIntro,yearComplete,callAnswered;\n        String feedback="",weekendChoice="";',"state fields")
rep('            bagMask=prefs.getInt("school_player_bag_mask",0);miniHits=prefs.getInt("school_player_mini_hits",0);homeStep=prefs.getInt("school_player_home_step",0);dinnerBites=prefs.getInt("school_player_dinner_bites",0);weekendChoice=prefs.getString("school_player_weekend_choice","");mistakes=Math.max(0,prefs.getInt("school_mistakes",0));','            bagMask=prefs.getInt("school_player_bag_mask",0);miniHits=prefs.getInt("school_player_mini_hits",0);homeStep=prefs.getInt("school_player_home_step",0);dinnerBites=prefs.getInt("school_player_dinner_bites",0);weekendChoice=prefs.getString("school_player_weekend_choice","");mistakes=Math.max(0,prefs.getInt("school_mistakes",0));\n            swimLaps=prefs.getInt("school_player_swim_laps",0);swimWarmth=prefs.getInt("school_player_swim_warmth",0);callAnswered=prefs.getBoolean("school_player_call_answered",false);',"load phone/swim state")
rep('        void resetMiniForDate(){bagMask=0;miniHits=0;homeStep=0;dinnerBites=0;feedback="";weekendChoice="";prefs.edit().putInt("school_player_bag_mask",0).putInt("school_player_mini_hits",0).putInt("school_player_home_step",0).putInt("school_player_dinner_bites",0).putString("school_player_weekend_choice","").apply();}','        void resetMiniForDate(){bagMask=0;miniHits=0;homeStep=0;dinnerBites=0;swimLaps=0;swimWarmth=0;callAnswered=false;feedback="";weekendChoice="";prefs.edit().putInt("school_player_bag_mask",0).putInt("school_player_mini_hits",0).putInt("school_player_home_step",0).putInt("school_player_dinner_bites",0).putInt("school_player_swim_laps",0).putInt("school_player_swim_warmth",0).putBoolean("school_player_call_answered",false).putString("school_player_weekend_choice","").apply();}',"daily reset")
rep('        @Override protected void onDraw(Canvas c){super.onDraw(c);drawBackground(c);drawHeader(c);if(stage==INTRO){drawIntro(c);return;}if(stage==YEAR_DONE){drawYearDone(c);return;}if(stage==DONE){drawDone(c);return;}if(stage==BONUS){drawBonus(c);return;}if(stage==WEEKEND){drawWeekendChoice(c);return;}if(stage==WEEKEND_MINI){drawWeekendMini(c);return;}if(stage==MORNING){drawMorning(c);return;}if(stage==LESSON1){drawLesson(c,false);return;}if(stage==BREAK){drawBreak(c);return;}if(stage==LESSON2){drawLesson(c,true);return;}if(stage==HOME){drawHome(c);return;}drawDinner(c);}','        @Override protected void onDraw(Canvas c){super.onDraw(c);drawBackground(c);drawHeader(c);if(stage==INTRO){drawIntro(c);return;}if(stage==YEAR_DONE){drawYearDone(c);return;}if(stage==DONE){drawDone(c);return;}if(stage==BONUS){drawBonus(c);return;}if(stage==WEEKEND){drawWeekendChoice(c);return;}if(stage==WEEKEND_MINI){drawWeekendMini(c);return;}if(stage==MORNING){drawMorning(c);return;}if(stage==LESSON1){drawLesson(c,false);return;}if(stage==CALL||stage==CALL_TALK){drawPhoneCall(c);return;}if(stage==BREAK){drawBreak(c);return;}if(stage==LESSON2){drawLesson(c,true);return;}if(stage==HOME){drawHome(c);return;}drawDinner(c);}',"onDraw phone stage")
s=s.replace('"ЕТАП 1/6 • РАНОК"','"ЕТАП 1/7 • РАНОК"').replace('"ЕТАП "+(second?"4":"2")+"/6 • "','"ЕТАП "+(second?"5":"2")+"/7 • "').replace('"ЕТАП 3/6 • ПЕРЕРВА"','"ЕТАП 4/7 • ПЕРЕРВА"').replace('"ЕТАП 5/6 • ДОРОГА ДОДОМУ"','"ЕТАП 6/7 • ДОРОГА ДОДОМУ"').replace('"ЕТАП 6/6 • ВЕЧЕРЯ "+schoolOrdinal()+"/5"','"ЕТАП 7/7 • ВЕЧЕРЯ "+schoolOrdinal()+"/5"')
insert_before='        void movingTarget(RectF r){float zoneTop=r.top+dp(130),zoneBottom=r.bottom-dp(150);long ms=SystemClock.elapsedRealtime()+miniHits*737L;'
phone_code='        String callLine(){switch(schoolOrdinal()){case 1:return"Ти вже в класі? Не забудь поїсти після школи.";case 2:return"Після уроків забери рукавички й не загуби моркву.";case 3:return"Як там урок про тепло? Тільки сам не розтань.";case 4:return"Передай Іскрику привіт. Побачимось увечері.";default:return"Останній навчальний день. Після школи чекає вечеря.";}}\n        void drawPhoneCall(Canvas c){RectF r=card();cardBase(c,r);centerText(c,"ЕТАП 3/7 • ТЕЛЕФОН У ШКОЛІ",r.top+dp(28),7,Color.rgb(111,132,139));RectF phone=new RectF(r.centerX()-dp(92),r.top+dp(68),r.centerX()+dp(92),r.top+dp(315));p.setColor(Color.rgb(35,45,51));c.drawRoundRect(phone,dp(28),dp(28),p);p.setColor(Color.rgb(225,244,250));c.drawCircle(phone.centerX(),phone.top+dp(72),dp(34),p);centerTextAt(c,"М",phone.centerX(),phone.top+dp(81),18,Color.rgb(57,118,148));centerTextAt(c,"МАМА",phone.centerX(),phone.top+dp(128),10,Color.WHITE);if(stage==CALL){centerTextAt(c,"ВХІДНИЙ ДЗВІНОК",phone.centerX(),phone.top+dp(157),6.6f,Color.rgb(191,209,216));acceptBtn.set(phone.left+dp(18),phone.bottom-dp(72),phone.centerX()-dp(7),phone.bottom-dp(20));declineBtn.set(phone.centerX()+dp(7),phone.bottom-dp(72),phone.right-dp(18),phone.bottom-dp(20));p.setColor(Color.rgb(69,156,104));c.drawRoundRect(acceptBtn,dp(18),dp(18),p);p.setColor(Color.rgb(190,82,76));c.drawRoundRect(declineBtn,dp(18),dp(18),p);centerTextAt(c,"ВІДПОВІСТИ",acceptBtn.centerX(),acceptBtn.centerY()+dp(3),6.4f,Color.WHITE);centerTextAt(c,"СКИНУТИ",declineBtn.centerX(),declineBtn.centerY()+dp(3),6.4f,Color.WHITE);action.setEmpty();}else{centerTextAt(c,callLine(),phone.centerX(),phone.top+dp(172),6.4f,Color.rgb(225,236,240));centerTextAt(c,"Короткий дзвінок на великій перерві.",phone.centerX(),phone.top+dp(203),5.9f,Color.rgb(171,195,204));button(c,"ЗАВЕРШИТИ РОЗМОВУ");}drawTeacher(c,r.left+dp(74),r.bottom-dp(34),dp(27));drawHero(c,r.right-dp(78),r.bottom-dp(34),dp(29));}\n\n'
if insert_before not in s: raise SystemExit("v18.6 phone/swim patch failed: phone insertion anchor")
s=s.replace(insert_before,phone_code+insert_before,1)
start=s.find('        void drawWeekendChoice(Canvas c){');end=s.find('        void drawBonus(Canvas c){',start)
if start<0 or end<0: raise SystemExit("v18.6 phone/swim patch failed: weekend draw block")
weekend_code='        void drawWeekendChoice(Canvas c){RectF r=card();cardBase(c,r);String which=calendarDow==Calendar.SATURDAY?"СУБОТА":"НЕДІЛЯ";centerText(c,which+" • ВИХІДНИЙ "+(weekendDone+1)+"/2",r.top+dp(30),7,Color.rgb(109,132,140));centerText(c,"СЬОГОДНІ — ПЛАВАННЯ",r.top+dp(72),19,Color.rgb(43,105,139));centerText(c,"Малого ведемо в крижаний басейн для сніговиків.",r.top+dp(106),7.4f,Color.rgb(99,125,136));centerText(c,"Вода тримається біля 0°C: пливемо, але не даємо їй нагрітися.",r.top+dp(132),6.8f,Color.rgb(99,125,136));p.setColor(Color.rgb(127,205,232));RectF pool=new RectF(r.left+dp(34),r.top+dp(175),r.right-dp(34),r.top+dp(330));c.drawRoundRect(pool,dp(34),dp(34),p);p.setColor(Color.rgb(224,247,252));for(int i=0;i<7;i++)c.drawCircle(pool.left+dp(28)+i*(pool.width()-dp(56))/6f,pool.top+dp(26)+(i%2)*dp(18),dp(8),p);drawHero(c,pool.centerX()-dp(38),pool.bottom-dp(18),dp(31));drawFriend(c,pool.centerX()+dp(52),pool.bottom-dp(18),dp(25));button(c,"ВЕСТИ МАЛОГО НА ПЛАВАННЯ");}\n        void drawWeekendMini(Canvas c){RectF r=card();cardBase(c,r);int targetLaps=weekendDone==0?5:6;centerText(c,"КРИЖАНИЙ БАСЕЙН • "+dayName(),r.top+dp(28),7,Color.rgb(109,132,140));centerText(c,weekendDone==0?"ПЕРШЕ ПЛАВАННЯ":"ПЛАВАННЯ ЗІ СНІЖИКОМ",r.top+dp(68),17,Color.rgb(43,105,139));centerText(c,"Зроби "+targetLaps+" гребків. Якщо вода теплішає — додай лід.",r.top+dp(98),7.1f,Color.rgb(99,125,136));float waterTop=r.top+dp(133),waterBottom=r.top+dp(315);p.setColor(swimWarmth>=3?Color.rgb(238,194,181):Color.rgb(130,207,234));RectF pool=new RectF(r.left+dp(28),waterTop,r.right-dp(28),waterBottom);c.drawRoundRect(pool,dp(32),dp(32),p);for(int i=0;i<6;i++){p.setColor(Color.argb(195,238,251,255));c.drawCircle(pool.left+dp(28)+i*(pool.width()-dp(56))/5f,pool.top+dp(26)+(i%2)*dp(20),dp(7),p);}drawHero(c,pool.centerX(),pool.bottom-dp(15),dp(34));centerText(c,"Гребки "+swimLaps+"/"+targetLaps+" • вода "+swimWarmth+"°C",r.top+dp(344),8,swimWarmth>=3?Color.rgb(177,78,67):Color.rgb(54,116,145));if(swimWarmth>=3)centerText(c,"Занадто тепло — спочатку додай лід.",r.top+dp(369),6.8f,Color.rgb(177,78,67));swimColdBtn.set(r.left+dp(22),r.bottom-dp(132),r.centerX()-dp(7),r.bottom-dp(78));swimStrokeBtn.set(r.centerX()+dp(7),r.bottom-dp(132),r.right-dp(22),r.bottom-dp(78));p.setColor(Color.rgb(95,178,210));c.drawRoundRect(swimColdBtn,dp(18),dp(18),p);p.setColor(swimWarmth>=3?Color.rgb(194,205,209):Color.rgb(48,132,174));c.drawRoundRect(swimStrokeBtn,dp(18),dp(18),p);centerTextAt(c,"+ ЛІД",swimColdBtn.centerX(),swimColdBtn.centerY()+dp(3),7.2f,Color.WHITE);centerTextAt(c,"ГРЕБОК",swimStrokeBtn.centerX(),swimStrokeBtn.centerY()+dp(3),7.2f,Color.WHITE);if(swimLaps>=targetLaps)button(c,"ВИТЕРТИСЯ Й ДОДОМУ");else action.setEmpty();}\n'
s=s[:start]+weekend_code+s[end:]
rep('        void persistMini(){prefs.edit().putInt("school_player_bag_mask",bagMask).putInt("school_player_mini_hits",miniHits).putInt("school_player_home_step",homeStep).putInt("school_player_dinner_bites",dinnerBites).putString("school_player_weekend_choice",weekendChoice).apply();}','        void persistMini(){prefs.edit().putInt("school_player_bag_mask",bagMask).putInt("school_player_mini_hits",miniHits).putInt("school_player_home_step",homeStep).putInt("school_player_dinner_bites",dinnerBites).putInt("school_player_swim_laps",swimLaps).putInt("school_player_swim_warmth",swimWarmth).putBoolean("school_player_call_answered",callAnswered).putString("school_player_weekend_choice",weekendChoice).apply();}',"persist phone/swim state")
rep('if(i==correct(false)){SoundFx.play(ctx,SoundFx.CORRECT);buzz(18);setStage(BREAK);}','if(i==correct(false)){SoundFx.play(ctx,SoundFx.CORRECT);buzz(18);setStage(CALL);SoundFx.play(ctx,SoundFx.PHONE);}',"route lesson 1 into phone call")
anchor='}else if(stage==BREAK){movingTarget(card());'
phone_touch='}else if(stage==CALL){if(acceptBtn.contains(x,y)){callAnswered=true;persistMini();SoundFx.play(ctx,SoundFx.PHONE);setStage(CALL_TALK);return true;}if(declineBtn.contains(x,y)){callAnswered=false;persistMini();prefs.edit().putInt("school_calls_missed",prefs.getInt("school_calls_missed",0)+1).apply();setStage(BREAK);return true;}return true;}else if(stage==CALL_TALK){if(action.contains(x,y)){prefs.edit().putInt("school_calls_answered",prefs.getInt("school_calls_answered",0)+1).apply();setStage(BREAK);return true;}return true;}else if(stage==BREAK){movingTarget(card());'
if anchor not in s: raise SystemExit("v18.6 phone/swim patch failed: call touch anchor")
s=s.replace(anchor,phone_touch,1)
old='}else if(stage==WEEKEND){String[] o=calendarDow==Calendar.SATURDAY?new String[]{"Санчата","Прогулянка","Сніжки"}:new String[]{"Спогади","Зібрати речі","Час зі Сніжиком"};for(int i=0;i<3;i++)if(choices[i].contains(x,y)){weekendChoice=o[i];miniHits=0;persistMini();setStage(WEEKEND_MINI);return true;}}else if(stage==WEEKEND_MINI){movingTarget(card());if(target.contains(x,y)&&miniHits<4){miniHits++;persistMini();SoundFx.play(ctx,SoundFx.PLAY);buzz(9);invalidate();return true;}if(miniHits>=4&&action.contains(x,y)){finishCountedDay();return true;}}'
new='}else if(stage==WEEKEND){if(action.contains(x,y)){weekendChoice="Крижане плавання";swimLaps=0;swimWarmth=0;persistMini();setStage(WEEKEND_MINI);SoundFx.play(ctx,SoundFx.SLED);return true;}}else if(stage==WEEKEND_MINI){int targetLaps=weekendDone==0?5:6;if(swimColdBtn.contains(x,y)){swimWarmth=Math.max(0,swimWarmth-2);persistMini();SoundFx.play(ctx,SoundFx.CRUNCH);buzz(8);invalidate();return true;}if(swimStrokeBtn.contains(x,y)&&swimLaps<targetLaps){if(swimWarmth>=3){wrong("Вода потепліла. Додай лід, щоб малий не почав танути.");return true;}swimLaps++;swimWarmth++;persistMini();SoundFx.play(ctx,SoundFx.PLAY);buzz(9);invalidate();return true;}if(swimLaps>=targetLaps&&action.contains(x,y)){finishCountedDay();return true;}}'
if old not in s: raise SystemExit("v18.6 phone/swim patch failed: weekend touch block")
s=s.replace(old,new,1)
school_path.write_text(s,encoding="utf-8")
g=gradle_path.read_text(encoding="utf-8")
g=re.sub(r'versionCode\s+\d+','versionCode 39',g);g=re.sub(r'versionName\s+"[^"]+"','versionName "18.6"',g);gradle_path.write_text(g,encoding="utf-8")
print("Applied SnowmanGame v18.6: weekday school calls and weekend ice-pool swimming")
